import json
import subprocess
import os

"""
This script downloads files based on the json file generated by save_search_result.py
"""

file_location = input('json files location: ')
part = input('specify part (optional, int): ')


file_names = os.listdir(file_location)

for file_name in file_names:
    with open(f'{file_location}/{file_name}', 'r+') as file:

        data = json.load(file)
        urls = [d['url'].split('?')[0] for d in data]

        for index, url in enumerate(urls):
            url = url if not part else url + f'?p={part}'
            subprocess.run(['you-get', '--format=flv360', url])
